"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['src/main.py']
DATA_FILES = []
OPTIONS = {}

setup(
    name='viking',
    version='1.0.0',
    description='Password manager tool',
    author='Juan Carlos Fiorenzano',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    install_requires=['cryptography==2.3.1']
)
